### PR TITLE
Don't try to index fulltext for Audio recordings

### PR DESCRIPTION
**Pull request by marlo-longley**

### CODE REVIEW

**Review by jcoyne — CHANGES_REQUESTED** [review]
Won't there just be no data in the file?  Why do we need an extra conditional?

**Comment by marlo-longley** [comment]
No text file is being created at all now @jcoyne

**Comment by jcoyne** [comment]
Right. since there's no file, why do we need a complex query? It's just going to say "no file -- skip this one"

**Comment by marlo-longley** [comment]
Getting all the warnings about missing file for 4500 druids is confusing. It makes it impossible to see if there is a valid warning for a missing file.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
